// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMcMXegZ47_hwU9vIxMAXTlRQ3rdYIAwI',
    appId: '1:1036487567463:web:6d453d837dacd4a9c9ccc2',
    messagingSenderId: '1036487567463',
    projectId: 'mynotes-flutter-test0',
    authDomain: 'mynotes-flutter-test0.firebaseapp.com',
    storageBucket: 'mynotes-flutter-test0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmHWN8-xtLPIkFaTpkSKisdMqz0BeKOe8',
    appId: '1:1036487567463:android:aea9a8c08f11df24c9ccc2',
    messagingSenderId: '1036487567463',
    projectId: 'mynotes-flutter-test0',
    storageBucket: 'mynotes-flutter-test0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4-Qix-SRoFHL2Y6YK4AilrcoyyHsA5xU',
    appId: '1:1036487567463:ios:b1133b8140b40fdec9ccc2',
    messagingSenderId: '1036487567463',
    projectId: 'mynotes-flutter-test0',
    storageBucket: 'mynotes-flutter-test0.appspot.com',
    iosClientId: '1036487567463-stavh4uoqenpo5ahuf46orm3bb4c5cvi.apps.googleusercontent.com',
    iosBundleId: 'com.todoapp.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4-Qix-SRoFHL2Y6YK4AilrcoyyHsA5xU',
    appId: '1:1036487567463:ios:b1133b8140b40fdec9ccc2',
    messagingSenderId: '1036487567463',
    projectId: 'mynotes-flutter-test0',
    storageBucket: 'mynotes-flutter-test0.appspot.com',
    iosClientId: '1036487567463-stavh4uoqenpo5ahuf46orm3bb4c5cvi.apps.googleusercontent.com',
    iosBundleId: 'com.todoapp.mynotes',
  );
}
